
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CADENA CARACTER COLON COMMA EDAD FECHA FECHA_FORMA FECHA_HORA FECHA_NAC FECHA_VALIDACION FOLIO LKEY NOMBRE NUM PACIENTE RKEY SEXOS : LKEY A RKEYA : FOLIO COLON NUM COMMA BB : FECHA_FORMA COLON FECHA_HORA COMMA CC : FECHA_VALIDACION COLON FECHA_HORA COMMA DD : PACIENTE COLON LKEY E RKEYE : NOMBRE COLON CADENA COMMA FF : FECHA_NAC COLON FECHA COMMA GG : SEXO COLON CARACTER COMMA HH : EDAD COLON NUM'
    
_lr_action_items = {'LKEY':([0,21,],[2,22,]),'$end':([1,5,],[0,-1,]),'FOLIO':([2,],[4,]),'RKEY':([3,9,14,19,23,25,29,34,39,42,],[5,-2,-3,-4,25,-5,-6,-7,-8,-9,]),'COLON':([4,10,15,20,24,30,35,40,],[6,11,16,21,26,31,36,41,]),'NUM':([6,41,],[7,42,]),'COMMA':([7,12,17,27,32,37,],[8,13,18,28,33,38,]),'FECHA_FORMA':([8,],[10,]),'FECHA_HORA':([11,16,],[12,17,]),'FECHA_VALIDACION':([13,],[15,]),'PACIENTE':([18,],[20,]),'NOMBRE':([22,],[24,]),'CADENA':([26,],[27,]),'FECHA_NAC':([28,],[30,]),'FECHA':([31,],[32,]),'SEXO':([33,],[35,]),'CARACTER':([36,],[37,]),'EDAD':([38,],[40,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[1,]),'A':([2,],[3,]),'B':([8,],[9,]),'C':([13,],[14,]),'D':([18,],[19,]),'E':([22,],[23,]),'F':([28,],[29,]),'G':([33,],[34,]),'H':([38,],[39,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> LKEY A RKEY','S',3,'p_S','parser.py',7),
  ('A -> FOLIO COLON NUM COMMA B','A',5,'p_folio','parser.py',11),
  ('B -> FECHA_FORMA COLON FECHA_HORA COMMA C','B',5,'p_fecha_forma','parser.py',15),
  ('C -> FECHA_VALIDACION COLON FECHA_HORA COMMA D','C',5,'p_fecha_validacion','parser.py',19),
  ('D -> PACIENTE COLON LKEY E RKEY','D',5,'p_paciente','parser.py',23),
  ('E -> NOMBRE COLON CADENA COMMA F','E',5,'p_nombre','parser.py',27),
  ('F -> FECHA_NAC COLON FECHA COMMA G','F',5,'p_fecha_nac','parser.py',31),
  ('G -> SEXO COLON CARACTER COMMA H','G',5,'p_sexo','parser.py',35),
  ('H -> EDAD COLON NUM','H',3,'p_edad','parser.py',39),
]
